name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.0'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Set up Code Climate test reporter
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: 56d2e4890ee24451b85050b0364f1d1aa92462cdd296dfb4dd38928427e3ce93
      with:
        coverageCommand: bundle exec rake test
        debug: true
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake test
